import type { BenchmarkProfile, BenchmarkScenario, FindingExpectation, ForbiddenFinding } from "./types";

export const BENCHMARK_VERSION = "1.0.0";

export const PROFILES: BenchmarkProfile[] = [
  { id: "clean", description: "Clean static, multi-page, responsive, form, SPA, and canonical redirect controls", entryPath: "/", smoke: true },
  { id: "document", description: "SEO, document structure, language, image, viewport, heading, and ID facts", entryPath: "/", smoke: true },
  { id: "accessibility", description: "Accessible-name and axe-supported deterministic accessibility controls", entryPath: "/", smoke: false },
  { id: "runtime", description: "Console, uncaught exception, resource failure, and diagnostic evidence controls", entryPath: "/", smoke: true },
  { id: "navigation", description: "HTTP status, transport failure, redirect chain, and redirect-loop behavior", entryPath: "/", smoke: false },
  { id: "security", description: "Existing security-header checks and finding identity/deduplication", entryPath: "/", smoke: false },
];

const expectation = (value: FindingExpectation) => value;
const forbidden = (id: string, reason: string, value: Omit<ForbiddenFinding, "id" | "reason">): ForbiddenFinding => ({ id, reason, ...value });
const scenario = (value: BenchmarkScenario): BenchmarkScenario => value;

export const SCENARIOS: BenchmarkScenario[] = [
  scenario({ id: "clean-static", profileId: "clean", category: "clean", description: "A complete static document stays free of deterministic findings.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("clean-static-any", "Clean static page must not receive a finding.", { pagePath: "/clean-static" })], expectedPage: { path: "/clean-static", status: 200, noFindings: true } }),
  scenario({ id: "clean-multipage", profileId: "clean", category: "clean", description: "A clean multi-page root does not invent blockers.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("clean-root-critical", "Clean root must not receive a blocker.", { pagePath: "/", severity: "CRITICAL" })], expectedPage: { path: "/", status: 200, noFindings: true }, expectedScan: { gate: "PASS", verdict: "READY TO SHIP" } }),
  scenario({ id: "clean-responsive", profileId: "clean", category: "clean", description: "A responsive layout does not trigger horizontal overflow.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("clean-overflow", "Responsive control must not overflow.", { ruleId: "horizontal-overflow", pagePath: "/clean-responsive" })], expectedPage: { path: "/clean-responsive", status: 200, noFindings: true } }),
  scenario({ id: "clean-form", profileId: "clean", category: "accessibility", description: "A labelled form control remains clean.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("clean-form-label", "Labelled control must not be reported.", { ruleId: "unlabeled-control", pagePath: "/clean-form" })], expectedPage: { path: "/clean-form", status: 200, noFindings: true } }),
  scenario({ id: "clean-spa", profileId: "clean", category: "clean", description: "A deterministic client-rendered route stays clean.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("clean-spa-runtime", "Controlled SPA must not emit runtime findings.", { pagePath: "/clean-spa", category: "browser" })], expectedPage: { path: "/clean-spa", status: 200, noFindings: true } }),
  scenario({ id: "clean-canonical-redirect", profileId: "clean", category: "http-navigation", description: "A one-hop same-origin canonical redirect is accepted without a broken-link finding.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("canonical-broken", "A valid canonical redirect is not broken.", { ruleId: "broken-link", pagePath: "/clean-static" })], expectedPage: { path: "/clean-static", status: 200, redirects: 1 } }),
  scenario({ id: "clean-valid-metadata", profileId: "clean", category: "seo-document", description: "Valid title, description, language, viewport, and h1 stay clean.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("clean-doc-quality", "Valid document facts must not trigger SEO/accessibility rules.", { pagePath: "/clean-static", category: "seo" })] }),

  scenario({ id: "document-missing-title", profileId: "document", category: "seo-document", description: "Missing title produces one critical DOM finding.", classification: "deterministic", expectedFindings: [expectation({ id: "missing-title", ruleId: "missing-title", severity: "CRITICAL", pagePath: "/missing-title", evidence: { source: "dom", required: ["url"] } })], forbiddenFindings: [] }),
  scenario({ id: "document-missing-description", profileId: "document", category: "seo-document", description: "Missing meta description produces one notice.", classification: "deterministic", expectedFindings: [expectation({ id: "missing-description", ruleId: "missing-description", severity: "NOTICE", pagePath: "/missing-description", evidence: { source: "dom", required: ["url"] } })], forbiddenFindings: [] }),
  scenario({ id: "document-missing-h1", profileId: "document", category: "seo-document", description: "Missing primary heading produces one warning.", classification: "deterministic", expectedFindings: [expectation({ id: "missing-h1", ruleId: "missing-h1", severity: "WARNING", pagePath: "/missing-h1", evidence: { source: "dom", required: ["url"] } })], forbiddenFindings: [] }),
  scenario({ id: "document-multiple-h1", profileId: "document", category: "seo-document", description: "Multiple h1 elements produce a counted notice.", classification: "deterministic", expectedFindings: [expectation({ id: "multiple-h1", ruleId: "multiple-h1", severity: "NOTICE", pagePath: "/multiple-h1", evidence: { source: "dom", required: ["url", "value"], value: 2 } })], forbiddenFindings: [] }),
  scenario({ id: "document-missing-lang", profileId: "document", category: "accessibility", description: "Missing document language produces a warning without duplicate axe penalty.", classification: "deterministic", expectedFindings: [expectation({ id: "missing-lang", ruleId: "missing-lang", severity: "WARNING", pagePath: "/missing-lang", evidence: { source: "dom", required: ["url"] } })], forbiddenFindings: [forbidden("missing-lang-axe", "Manual language rule owns this defect.", { ruleId: "axe-violation", pagePath: "/missing-lang" })] }),
  scenario({ id: "document-missing-alt", profileId: "document", category: "accessibility", description: "Missing image alternative text includes the element selector.", classification: "deterministic", expectedFindings: [expectation({ id: "missing-alt", ruleId: "missing-alt", severity: "WARNING", pagePath: "/missing-alt", selectorIncludes: "#hero", evidence: { source: "dom", required: ["url", "selector", "value"] } })], forbiddenFindings: [forbidden("missing-alt-axe", "Manual image rule owns this defect.", { ruleId: "axe-violation", pagePath: "/missing-alt" })] }),
  scenario({ id: "document-missing-viewport", profileId: "document", category: "seo-document", description: "Missing mobile viewport produces one release-blocking finding.", classification: "deterministic", expectedFindings: [expectation({ id: "missing-viewport", ruleId: "missing-viewport", severity: "CRITICAL", pagePath: "/missing-viewport", evidence: { source: "dom", required: ["url"] } })], forbiddenFindings: [] }),
  scenario({ id: "document-heading-order", profileId: "document", category: "seo-document", description: "An h1 to h3 jump records the skipped heading selector.", classification: "deterministic", expectedFindings: [expectation({ id: "heading-order", ruleId: "heading-order", severity: "WARNING", pagePath: "/heading-order", selectorIncludes: "#jump", evidence: { source: "dom", required: ["url", "selector", "value", "excerpt"] } })], forbiddenFindings: [forbidden("heading-axe-duplicate", "Manual hierarchy rule owns this defect.", { ruleId: "axe-violation", pagePath: "/heading-order" })] }),
  scenario({ id: "document-duplicate-id", profileId: "document", category: "accessibility", description: "A duplicated ID is one warning with two occurrences.", classification: "deterministic", expectedFindings: [expectation({ id: "duplicate-id", ruleId: "duplicate-id", severity: "WARNING", pagePath: "/duplicate-id", selectorIncludes: "#shared", expectedOccurrences: 2, evidence: { source: "dom", required: ["url", "selector", "value", "excerpt"] } })], forbiddenFindings: [forbidden("duplicate-id-axe", "Manual duplicate-ID rule owns this defect.", { ruleId: "axe-violation", pagePath: "/duplicate-id" })] }),
  scenario({ id: "document-release-verdict", profileId: "document", category: "release-reliability", description: "Supported critical document failures block the default release gate.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [], expectedScan: { gate: "FAIL", verdict: "BLOCKED" } }),

  scenario({ id: "accessibility-unlabeled-control", profileId: "accessibility", category: "accessibility", description: "An email input without a name is a critical release blocker with selector evidence.", classification: "deterministic", expectedFindings: [expectation({ id: "unlabeled-control", ruleId: "unlabeled-control", severity: "CRITICAL", pagePath: "/unlabeled-control", selectorIncludes: "#email", evidence: { source: "dom", required: ["url", "selector", "value"] } })], forbiddenFindings: [forbidden("unlabeled-axe", "Manual accessible-name rule owns this defect.", { ruleId: "axe-violation", pagePath: "/unlabeled-control" })], expectedScan: { gate: "FAIL", verdict: "BLOCKED" } }),
  scenario({ id: "accessibility-contrast", profileId: "accessibility", category: "accessibility", description: "Obvious text contrast failure is captured by axe as a warning.", classification: "deterministic", expectedFindings: [expectation({ id: "color-contrast", ruleId: "axe-violation", severity: "WARNING", pagePath: "/contrast", selectorIncludes: "#low-contrast", evidence: { source: "axe", required: ["url", "selector", "axeNode", "excerpt"] } })], forbiddenFindings: [] }),
  scenario({ id: "accessibility-labelled-control", profileId: "accessibility", category: "clean", description: "A labelled control does not produce accessible-name findings.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("labelled-control", "The named control is the clean accessibility control.", { pagePath: "/labelled-control", category: "accessibility" })], expectedPage: { path: "/labelled-control", status: 200, noFindings: true } }),
  scenario({ id: "accessibility-evidence-source", profileId: "accessibility", category: "evidence", description: "Accessibility findings retain element-specific evidence rather than generic page text.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("generic-axe-evidence", "Axe findings must not have empty selectors.", { ruleId: "axe-violation", selectorIncludes: "" })] }),

  scenario({ id: "runtime-console-error", profileId: "runtime", category: "release-reliability", description: "An explicit console error is a warning with captured message.", classification: "deterministic", expectedFindings: [expectation({ id: "console-error", ruleId: "console-error", severity: "WARNING", pagePath: "/console", consoleIncludes: "fixture console error", evidence: { source: "console", required: ["url", "consoleMessage", "excerpt", "value"], value: 1 } })], forbiddenFindings: [] }),
  scenario({ id: "runtime-console-warning-dedupe", profileId: "runtime", category: "identity-deduplication", description: "Three identical warnings become one finding with three occurrences.", classification: "deterministic", expectedFindings: [expectation({ id: "console-warning", ruleId: "console-warning", severity: "NOTICE", pagePath: "/console", consoleIncludes: "fixture repeated warning", expectedOccurrences: 3, evidence: { source: "console", required: ["url", "consoleMessage", "excerpt", "value"], value: 3 } })], forbiddenFindings: [] }),
  scenario({ id: "runtime-page-exception", profileId: "runtime", category: "release-reliability", description: "An uncaught page exception is critical and blocks release.", classification: "deterministic", expectedFindings: [expectation({ id: "page-error", ruleId: "page-error", severity: "CRITICAL", pagePath: "/page-error", consoleIncludes: "fixture uncaught exception", evidence: { source: "pageerror", required: ["url", "consoleMessage", "excerpt"] } })], forbiddenFindings: [], expectedScan: { gate: "FAIL", verdict: "BLOCKED" } }),
  ...(["image", "script", "stylesheet", "font", "fetch"] as const).map((resourceType) => scenario({
    id: `runtime-${resourceType}-failure`, profileId: "runtime", category: "release-reliability", description: `A failed ${resourceType} request is classified with resource evidence.`, classification: "deterministic",
    expectedFindings: [expectation({ id: `${resourceType}-request`, ruleId: "request-failure", severity: "NOTICE", pagePath: `/resource-${resourceType}`, requestPath: `/missing-${resourceType}`, expectedOccurrences: 1, evidence: { source: "network", required: ["url", "requestUrl", "resourceType", "httpStatus", "excerpt"], httpStatus: 404 } })],
    forbiddenFindings: [forbidden(`${resourceType}-console-duplicate`, "A network failure must not be double-reported as a generic console error.", { ruleId: "console-error", pagePath: `/resource-${resourceType}` })],
  })),
  scenario({ id: "runtime-sanitized-diagnostic", profileId: "runtime", category: "evidence", description: "Browser exception evidence does not expose local machine or Playwright paths.", classification: "deterministic", expectedFindings: [expectation({ id: "sanitized-page-error", ruleId: "page-error", severity: "CRITICAL", pagePath: "/sanitized-error", consoleIncludes: "fixture internal path", evidence: { source: "pageerror", required: ["url", "consoleMessage", "excerpt"] } })], forbiddenFindings: [] }),
  scenario({ id: "runtime-environmental-performance", profileId: "runtime", category: "performance-runtime", description: "Lighthouse and duration-derived findings are reported separately from deterministic accuracy.", classification: "environmental", expectedFindings: [], forbiddenFindings: [] }),

  scenario({ id: "navigation-404-status", profileId: "navigation", category: "http-navigation", description: "A 404 child produces critical page-status evidence.", classification: "deterministic", expectedFindings: [expectation({ id: "status-404", ruleId: "http-status", severity: "CRITICAL", pagePath: "/status-404", evidence: { source: "http", required: ["url", "httpStatus", "value"], httpStatus: 404, value: 404 } })], forbiddenFindings: [] }),
  scenario({ id: "navigation-404-link", profileId: "navigation", category: "release-reliability", description: "A discovered 404 destination is also one broken internal link.", classification: "deterministic", expectedFindings: [expectation({ id: "link-404", ruleId: "broken-link", severity: "WARNING", pagePath: "/status-404", evidence: { source: "http", required: ["url", "httpStatus", "value"], httpStatus: 404, value: 404 } })], forbiddenFindings: [] }),
  scenario({ id: "navigation-500-status", profileId: "navigation", category: "http-navigation", description: "A 500 child produces critical page-status evidence.", classification: "deterministic", expectedFindings: [expectation({ id: "status-500", ruleId: "http-status", severity: "CRITICAL", pagePath: "/status-500", evidence: { source: "http", required: ["url", "httpStatus", "value"], httpStatus: 500, value: 500 } })], forbiddenFindings: [] }),
  scenario({ id: "navigation-500-link", profileId: "navigation", category: "release-reliability", description: "A discovered 500 destination is one broken internal link.", classification: "deterministic", expectedFindings: [expectation({ id: "link-500", ruleId: "broken-link", severity: "WARNING", pagePath: "/status-500", evidence: { source: "http", required: ["url", "httpStatus", "value"], httpStatus: 500, value: 500 } })], forbiddenFindings: [] }),
  scenario({ id: "navigation-transport-status", profileId: "navigation", category: "http-navigation", description: "A closed transport produces a critical failed-page finding tied to the requested URL.", classification: "deterministic", expectedFindings: [expectation({ id: "transport-status", ruleId: "http-status", severity: "CRITICAL", pagePath: "/transport-close", evidence: { source: "http", required: ["url", "httpStatus", "value", "excerpt"], httpStatus: 0, value: 0 } })], forbiddenFindings: [] }),
  scenario({ id: "navigation-transport-link", profileId: "navigation", category: "release-reliability", description: "A closed child transport produces one broken link without fabricated DOM findings.", classification: "deterministic", expectedFindings: [expectation({ id: "transport-link", ruleId: "broken-link", severity: "WARNING", pagePath: "/transport-close", evidence: { source: "http", required: ["url", "httpStatus", "value", "excerpt"], httpStatus: 0, value: 0 } })], forbiddenFindings: [forbidden("transport-dom", "A failed document has no trustworthy DOM.", { pagePath: "/transport-close", category: "seo" })] }),
  scenario({ id: "navigation-valid-chain", profileId: "navigation", category: "http-navigation", description: "A bounded two-hop redirect chain completes without a broken-link finding.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("redirect-chain-broken", "A successful bounded redirect chain is not broken.", { ruleId: "broken-link", pagePath: "/redirect-final" })], expectedPage: { path: "/redirect-final", status: 200, redirects: 2, noFindings: true } }),
  scenario({ id: "navigation-loop", profileId: "navigation", category: "http-navigation", description: "A redirect loop terminates at the configured budget with failed-page evidence.", classification: "deterministic", expectedFindings: [expectation({ id: "redirect-loop-status", ruleId: "http-status", severity: "CRITICAL", pagePath: "/redirect-loop-a", evidence: { source: "http", required: ["url", "httpStatus", "value", "excerpt"] } }), expectation({ id: "redirect-loop-link", ruleId: "broken-link", severity: "WARNING", pagePath: "/redirect-loop-a", evidence: { source: "http", required: ["url", "httpStatus", "value", "excerpt"] } })], forbiddenFindings: [], expectedScan: { gate: "FAIL", verdict: "BLOCKED" } }),

  scenario({ id: "security-missing-csp", profileId: "security", category: "security-configuration", description: "Pages without CSP create one site-scoped notice.", classification: "deterministic", expectedFindings: [expectation({ id: "missing-csp", ruleId: "missing-csp", severity: "NOTICE", pagePath: "/missing-csp-a", expectedOccurrences: 2, expectedAffectedPages: 2, evidence: { source: "header", required: ["url"] } })], forbiddenFindings: [] }),
  scenario({ id: "security-present-csp", profileId: "security", category: "clean", description: "A page with CSP does not trigger the header rule.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("present-csp", "Present CSP must stay clean.", { ruleId: "missing-csp", pagePath: "/present-csp" })], expectedPage: { path: "/present-csp", status: 200, noFindings: true } }),
  scenario({ id: "security-http-hsts-boundary", profileId: "security", category: "security-configuration", description: "HSTS is not demanded from an HTTP-only local fixture.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("http-hsts", "HSTS is meaningful only on HTTPS.", { ruleId: "missing-hsts" })] }),
  scenario({ id: "dedupe-shared-resource", profileId: "security", category: "identity-deduplication", description: "The same failed resource across two pages is one underlying finding affecting two pages.", classification: "deterministic", expectedFindings: [expectation({ id: "shared-resource", ruleId: "request-failure", severity: "NOTICE", pagePath: "/shared-a", requestPath: "/shared-missing-script", expectedOccurrences: 2, expectedAffectedPages: 2, evidence: { source: "network", required: ["url", "requestUrl", "resourceType", "httpStatus", "excerpt"], httpStatus: 404 } })], forbiddenFindings: [] }),
  scenario({ id: "dedupe-repeated-resource", profileId: "security", category: "identity-deduplication", description: "Three identical fetch failures on one page are one finding with three occurrences.", classification: "deterministic", expectedFindings: [expectation({ id: "repeated-resource", ruleId: "request-failure", severity: "NOTICE", pagePath: "/repeated-resource", requestPath: "/repeated-missing", expectedOccurrences: 3, evidence: { source: "network", required: ["url", "requestUrl", "resourceType", "httpStatus", "excerpt"], httpStatus: 404 } })], forbiddenFindings: [] }),
  scenario({ id: "dedupe-network-console", profileId: "security", category: "identity-deduplication", description: "Browser-generated network console noise does not duplicate structured network evidence.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("shared-console-duplicate", "Structured network evidence owns resource load failures.", { ruleId: "console-error", consoleIncludes: "Failed to load resource" })] }),
  scenario({ id: "security-release-verdict", profileId: "security", category: "release-reliability", description: "Non-critical supported configuration findings produce warnings without blocking the default gate.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [], expectedScan: { gate: "PASS", verdict: "READY WITH WARNINGS" } }),
  scenario({ id: "security-evidence-identity", profileId: "security", category: "evidence", description: "Shared resource findings retain the failed endpoint and affected-page identity.", classification: "deterministic", expectedFindings: [], forbiddenFindings: [forbidden("empty-resource-evidence", "Resource evidence must identify its request URL.", { ruleId: "request-failure", requestPath: "" })] }),
];
