import Link from "next/link";

import type { ProjectRecord, ScanDelta, ScanRecord } from "@/lib/qr/types";
import { ArrowIcon } from "./icons";
import { issueAnchorId, signed } from "./report-model";

export function ComparisonWorkspace({ project, scan, target }: { project: ProjectRecord; scan: ScanRecord; target: "previous" | "baseline" }) {
  const delta = scan.comparisons[target] as ScanDelta | undefined;
  const available = (["previous", "baseline"] as const).filter((item) => Boolean(scan.comparisons[item]));
  const materialChanges = delta?.issues.items.filter((item) => item.status !== "UNCHANGED") ?? [];
  return <main id="main-content" className="control-page comparison-page">
    <nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/dashboard">Dashboard</Link><span>/</span><Link href={`/projects/${project.id}`}>{project.name}</Link><span>/</span><span aria-current="page">Comparison</span></nav>
    <header className="page-heading"><div><span className="eyebrow">Scan comparison</span><h1>What changed before release</h1><p>Only differences persisted by ALT QR are shown. Open a finding to inspect its captured evidence in the current report.</p></div><Link className="secondary-action" href={`/scan/${scan.id}`}>Open report<ArrowIcon /></Link></header>
    <nav className="comparison-tabs" aria-label="Comparison target">{available.map((item) => <Link key={item} href={`/scan/${scan.id}/compare?against=${item}`} aria-current={item === target ? "page" : undefined}>{item === "previous" ? "Previous scan" : "Project baseline"}</Link>)}</nav>
    {delta ? <>
      <section className="comparison-hero"><div><span>Score change</span><strong data-direction={delta.scoreDelta >= 0 ? "up" : "down"}>{signed(delta.scoreDelta)}</strong><small>Current score {scan.score?.overall ?? "—"}</small></div><div><span>Fixed</span><strong>{delta.issues.fixedCount}</strong><small>no longer detected</small></div><div><span>New</span><strong>{delta.issues.newCount}</strong><small>newly detected</small></div><div><span>Regressions</span><strong>{delta.issues.regressionCount}</strong><small>measurably worse</small></div><div><span>Visual difference</span><strong>{typeof delta.visualDifference === "number" ? `${delta.visualDifference.toFixed(2)}%` : "—"}</strong><small>{typeof delta.visualDifference === "number" ? "captured pixel change" : "not available"}</small></div></section>
      <section className="control-section" aria-labelledby="change-ledger-heading"><div className="section-bar"><div><span className="eyebrow">Change ledger</span><h2 id="change-ledger-heading">Fixed, new, and regressed findings</h2></div><p>{materialChanges.length} material {materialChanges.length === 1 ? "change" : "changes"}</p></div>{materialChanges.length ? <div className="comparison-ledger">{materialChanges.map((item) => { const issue = item.current ?? item.previous!; return <article key={`${item.fingerprint}-${item.status}`} data-status={item.status}><span>{item.status}</span><div><strong>{issue.title}</strong><p>{item.changes.length ? item.changes.join(" · ") : issue.description}</p><small>{issue.category} · {issue.severity.toLowerCase()} · {issue.affectedPageIds.length} affected {issue.affectedPageIds.length === 1 ? "page" : "pages"}</small></div>{item.current ? <Link href={`/scan/${scan.id}#${issueAnchorId(issue.ruleId, issue.scope, issue.title)}`}>Evidence<ArrowIcon /></Link> : <Link href={`/scan/${delta.baseScanId}`}>Previous report<ArrowIcon /></Link>}</article>; })}</div> : <div className="control-empty"><h2>No material issue changes</h2><p>The stored comparison records no fixed, new, changed, or regressed findings.</p></div>}</section>
      {Object.keys(delta.categoryDeltas).length ? <section className="control-panel comparison-categories" aria-labelledby="category-change-heading"><div className="panel-heading"><div><span className="eyebrow">Category movement</span><h2 id="category-change-heading">Score changes by area</h2></div></div><div>{Object.entries(delta.categoryDeltas).map(([category, value]) => <div key={category}><span>{category}</span><strong data-direction={(value ?? 0) >= 0 ? "up" : "down"}>{signed(value ?? 0)}</strong></div>)}</div></section> : null}
    </> : <div className="control-empty"><h2>No {target} comparison is available</h2><p>{target === "previous" ? "Complete another scan to compare this result with its predecessor." : "Set a completed scan as the project baseline, then rescan."}</p><Link className="primary-action" href={`/scan/${scan.id}`}>Return to report</Link></div>}
  </main>;
}
